services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
      - rabbitmq
    env_file:
      - .env
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: ${RABBITMQ_DEFAULT_USER}
      SPRING_RABBITMQ_PASSWORD: ${RABBITMQ_DEFAULT_PASS}
    volumes:
      - files_data:/home/dsm/senpe/default/files:rw

  db:
    image: postgres:17.7
    env_file:
      - .env   # usa variáveis do arquivo .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    env_file:
      - .env   # usa variáveis do arquivo .env
    ports:
      - "5050:80"
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  rabbitmq:
    image: rabbitmq:3-management
    env_file:
      - .env   # usa variáveis do arquivo .env
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  postgres_data:
  pgadmin_data:
  files_data: